### ISSUE TITLE
Issue-New IO interface for send/send_sw

### ISSUE THREAD

**Issue by ishida0415** [ishida0415/ton-ledger#10]
Automated Review Comments
Issues in src/handlers/get_app_name.c:
  - (1, 'Line exceeds 80 characters')
Issues in src/handlers/get_version.c:
  - (1, 'Line exceeds 80 characters')
Issues in src/io.c:
  - (14, 'Line exceeds 80 characters')

**Comment by PhantomFortune** [comment]
I got it.
