### ISSUE TITLE
Issue-Initial commit

### ISSUE THREAD

**Issue by ishida0415** [ishida0415/ton-ledger#3]
Automated Review Comments
Issues in Makefile:
  - (6, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
Issues in README.md:
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
Issues in src/dispatcher.c:
  - (6, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in src/handlers/get_app_name.c:
  - (6, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in src/handlers/get_version.c:
  - (6, 'Hardcoded string found')
  - (13, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
